/*
 * The voices that carry the police-call lines (PHONE_CALL_COPS, CALL_COPS_COMMIT, CALL_COPS_THREAT),
 * by ped model. A ped speaks in one of its model's voices; a model not listed has no voice with the
 * lines, and the witness speaks in a stand-in of the right gender instead.
 *
 * Generated from the game's speech catalogue (alexguirre's Speeches.cs): every voice with
 * PHONE_CALL_COPS, grouped by the model name the voice is named after.
 */
export const POLICE_CALL_VOICES: Readonly<Record<string, readonly string[]>> = Object.freeze({
	a_f_m_bevhills_02: ['A_F_M_BEVHILLS_02_WHITE_FULL_02'],
	a_f_m_bodybuild_01: ['A_F_M_BODYBUILD_01_BLACK_MINI_01', 'A_F_M_BODYBUILD_01_WHITE_MINI_01'],
	a_f_m_business_02: ['A_F_M_BUSINESS_02_WHITE_MINI_01'],
	a_f_m_eastsa_01: ['A_F_M_EASTSA_01_LATINO_MINI_01'],
	a_f_m_fatwhite_01: ['A_F_M_FATWHITE_01_WHITE_MINI_01'],
	a_f_m_salton_01: ['A_F_M_SALTON_01_WHITE_FULL_01', 'A_F_M_SALTON_01_WHITE_FULL_02', 'A_F_M_SALTON_01_WHITE_FULL_03', 'A_F_M_SALTON_01_WHITE_MINI_02', 'A_F_M_SALTON_01_WHITE_MINI_03'],
	a_f_m_tourist_01: ['A_F_M_TOURIST_01_WHITE_MINI_01'],
	a_f_o_genstreet_01: ['A_F_O_GENSTREET_01_WHITE_MINI_01'],
	a_f_o_indian_01: ['A_F_O_INDIAN_01_INDIAN_MINI_01'],
	a_f_o_salton_01: ['A_F_O_SALTON_01_WHITE_MINI_01'],
	a_f_y_bevhills_01: ['A_F_Y_BEVHILLS_01_WHITE_MINI_01'],
	a_f_y_bevhills_04: ['A_F_Y_BEVHILLS_04_WHITE_MINI_01'],
	a_f_y_business_03: ['A_F_Y_BUSINESS_03_CHINESE_MINI_01'],
	a_f_y_business_04: ['A_F_Y_BUSINESS_04_BLACK_MINI_01'],
	a_f_y_eastsa_03: ['A_F_Y_EASTSA_03_LATINO_FULL_01'],
	a_f_y_golfer_01: ['A_F_Y_GOLFER_01_WHITE_MINI_01'],
	a_f_y_hipster_01: ['A_F_Y_HIPSTER_01_WHITE_MINI_01'],
	a_f_y_indian_01: ['A_F_Y_INDIAN_01_INDIAN_MINI_01'],
	a_f_y_skater_01: ['A_F_Y_SKATER_01_WHITE_MINI_01'],
	a_f_y_tourist_02: ['A_F_Y_TOURIST_02_WHITE_MINI_01'],
	a_f_y_vinewood_01: ['A_F_Y_VINEWOOD_01_WHITE_MINI_01'],
	a_f_y_vinewood_02: ['A_F_Y_VINEWOOD_02_WHITE_MINI_01'],
	a_f_y_vinewood_03: ['A_F_Y_VINEWOOD_03_CHINESE_MINI_01'],
	a_m_m_beach_01: ['A_M_M_BEACH_01_WHITE_MINI_02'],
	a_m_m_beach_02: ['A_M_M_BEACH_02_WHITE_MINI_01'],
	a_m_m_eastsa_02: ['A_M_M_EASTSA_02_LATINO_MINI_01'],
	a_m_m_golfer_01: ['A_M_M_GOLFER_01_WHITE_MINI_01'],
	a_m_m_hasjew_01: ['A_M_M_HASJEW_01_WHITE_MINI_01'],
	a_m_m_hillbilly_01: ['A_M_M_HILLBILLY_01_WHITE_MINI_01', 'A_M_M_HILLBILLY_01_WHITE_MINI_02', 'A_M_M_HILLBILLY_01_WHITE_MINI_03'],
	a_m_m_hillbilly_02: ['A_M_M_HILLBILLY_02_WHITE_MINI_01', 'A_M_M_HILLBILLY_02_WHITE_MINI_02', 'A_M_M_HILLBILLY_02_WHITE_MINI_03'],
	a_m_m_indian_01: ['A_M_M_INDIAN_01_INDIAN_MINI_01'],
	a_m_m_ktown_01: ['A_M_M_KTOWN_01_KOREAN_MINI_01'],
	a_m_m_skater_01: ['A_M_M_SKATER_01_WHITE_MINI_01'],
	a_m_m_tranvest_01: ['A_M_M_TRANVEST_01_WHITE_MINI_01'],
	a_m_o_beach_01: ['A_M_O_BEACH_01_WHITE_MINI_01'],
	a_m_o_genstreet_01: ['A_M_O_GENSTREET_01_WHITE_MINI_01'],
	a_m_o_salton_01: ['A_M_O_SALTON_01_WHITE_MINI_01'],
	a_m_y_beach_01: ['A_M_Y_BEACH_01_WHITE_MINI_01'],
	a_m_y_busicas_01: ['A_M_Y_BUSICAS_01_WHITE_MINI_01'],
	a_m_y_business_01: ['A_M_Y_BUSINESS_01_WHITE_MINI_02'],
	a_m_y_business_03: ['A_M_Y_BUSINESS_03_WHITE_MINI_01'],
	a_m_y_epsilon_02: ['A_M_Y_EPSILON_02_WHITE_MINI_01'],
	a_m_y_gay_02: ['A_M_Y_GAY_02_WHITE_MINI_01'],
	a_m_y_genstreet_01: ['A_M_Y_GENSTREET_01_WHITE_MINI_01'],
	a_m_y_golfer_01: ['A_M_Y_GOLFER_01_WHITE_MINI_01'],
	a_m_y_hasjew_01: ['A_M_Y_HASJEW_01_WHITE_MINI_01'],
	a_m_y_hippy_01: ['A_M_Y_HIPPY_01_WHITE_MINI_01'],
	a_m_y_hipster_03: ['A_M_Y_HIPSTER_03_WHITE_MINI_01'],
	a_m_y_ktown_01: ['A_M_Y_KTOWN_01_KOREAN_MINI_01'],
	a_m_y_musclbeac_01: ['A_M_Y_MUSCLBEAC_01_WHITE_MINI_01'],
	a_m_y_salton_01: ['A_M_Y_SALTON_01_WHITE_MINI_01'],
	a_m_y_stwhi_01: ['A_M_Y_STWHI_01_WHITE_MINI_01'],
	a_m_y_stwhi_02: ['A_M_Y_STWHI_02_WHITE_MINI_01'],
	a_m_y_sunbathe_01: ['A_M_Y_SUNBATHE_01_WHITE_MINI_01'],
	a_m_y_vinewood_02: ['A_M_Y_VINEWOOD_02_WHITE_MINI_01'],
	a_m_y_vinewood_03: ['A_M_Y_VINEWOOD_03_WHITE_MINI_01'],
	a_m_y_vinewood_04: ['A_M_Y_VINEWOOD_04_WHITE_MINI_01'],
	mp_m_shopkeep_01: ['MP_M_SHOPKEEP_01_CHINESE_MINI_01', 'MP_M_SHOPKEEP_01_LATINO_MINI_01', 'MP_M_SHOPKEEP_01_PAKISTANI_MINI_01'],
	s_f_m_fembarber: ['S_F_M_FEMBARBER_BLACK_MINI_01'],
	s_f_m_genericcheapworker_01: ['S_F_M_GENERICCHEAPWORKER_01_LATINO_MINI_01', 'S_F_M_GENERICCHEAPWORKER_01_LATINO_MINI_02', 'S_F_M_GENERICCHEAPWORKER_01_LATINO_MINI_03'],
	s_f_m_ponsen_01: ['S_F_M_PONSEN_01_BLACK_01'],
	s_f_m_shop_high: ['S_F_M_SHOP_HIGH_WHITE_MINI_01'],
	s_f_y_airhostess_01: ['S_F_Y_AIRHOSTESS_01_BLACK_FULL_01', 'S_F_Y_AIRHOSTESS_01_BLACK_FULL_02', 'S_F_Y_AIRHOSTESS_01_WHITE_FULL_01', 'S_F_Y_AIRHOSTESS_01_WHITE_FULL_02'],
	s_f_y_baywatch_01: ['S_F_Y_BAYWATCH_01_BLACK_FULL_01', 'S_F_Y_BAYWATCH_01_BLACK_FULL_02', 'S_F_Y_BAYWATCH_01_WHITE_FULL_01', 'S_F_Y_BAYWATCH_01_WHITE_FULL_02'],
	s_f_y_genericcheapworker_01: ['S_F_Y_GENERICCHEAPWORKER_01_BLACK_MINI_01', 'S_F_Y_GENERICCHEAPWORKER_01_BLACK_MINI_02', 'S_F_Y_GENERICCHEAPWORKER_01_LATINO_MINI_01', 'S_F_Y_GENERICCHEAPWORKER_01_LATINO_MINI_02', 'S_F_Y_GENERICCHEAPWORKER_01_LATINO_MINI_03', 'S_F_Y_GENERICCHEAPWORKER_01_LATINO_MINI_04', 'S_F_Y_GENERICCHEAPWORKER_01_WHITE_MINI_01', 'S_F_Y_GENERICCHEAPWORKER_01_WHITE_MINI_02'],
	s_f_y_hooker_01: ['S_F_Y_HOOKER_01_WHITE_FULL_01', 'S_F_Y_HOOKER_01_WHITE_FULL_02', 'S_F_Y_HOOKER_01_WHITE_FULL_03'],
	s_f_y_hooker_02: ['S_F_Y_HOOKER_02_WHITE_FULL_01', 'S_F_Y_HOOKER_02_WHITE_FULL_02', 'S_F_Y_HOOKER_02_WHITE_FULL_03'],
	s_f_y_hooker_03: ['S_F_Y_HOOKER_03_BLACK_FULL_01', 'S_F_Y_HOOKER_03_BLACK_FULL_03'],
	s_f_y_pecker_01: ['S_F_Y_PECKER_01_WHITE_01'],
	s_f_y_shop_low: ['S_F_Y_SHOP_LOW_WHITE_MINI_01'],
	s_f_y_shop_mid: ['S_F_Y_SHOP_MID_WHITE_MINI_01'],
	s_m_m_ammucountry: ['S_M_M_AMMUCOUNTRY_WHITE_MINI_01'],
	s_m_m_ammucountry_01: ['S_M_M_AMMUCOUNTRY_01_WHITE_01'],
	s_m_m_autoshop_01: ['S_M_M_AUTOSHOP_01_WHITE_01'],
	s_m_m_genericcheapworker_01: ['S_M_M_GENERICCHEAPWORKER_01_LATINO_MINI_01', 'S_M_M_GENERICCHEAPWORKER_01_LATINO_MINI_02', 'S_M_M_GENERICCHEAPWORKER_01_LATINO_MINI_03', 'S_M_M_GENERICCHEAPWORKER_01_LATINO_MINI_04'],
	s_m_m_genericmechanic_01: ['S_M_M_GENERICMECHANIC_01_BLACK_MINI_01', 'S_M_M_GENERICMECHANIC_01_BLACK_MINI_02'],
	s_m_m_genericpostworker_01: ['S_M_M_GENERICPOSTWORKER_01_BLACK_MINI_01', 'S_M_M_GENERICPOSTWORKER_01_BLACK_MINI_02', 'S_M_M_GENERICPOSTWORKER_01_WHITE_MINI_01', 'S_M_M_GENERICPOSTWORKER_01_WHITE_MINI_02'],
	s_m_m_hairdress_01: ['S_M_M_HAIRDRESS_01_BLACK_01'],
	s_m_m_hairdresser_01: ['S_M_M_HAIRDRESSER_01_BLACK_MINI_01'],
	s_m_m_pilot_01: ['S_M_M_PILOT_01_BLACK_FULL_01', 'S_M_M_PILOT_01_BLACK_FULL_02', 'S_M_M_PILOT_01_WHITE_FULL_01', 'S_M_M_PILOT_01_WHITE_FULL_02'],
	s_m_y_airworker: ['S_M_Y_AIRWORKER_BLACK_FULL_01', 'S_M_Y_AIRWORKER_BLACK_FULL_02', 'S_M_Y_AIRWORKER_LATINO_FULL_01', 'S_M_Y_AIRWORKER_LATINO_FULL_02'],
	s_m_y_ammucity_01: ['S_M_Y_AMMUCITY_01_WHITE_01', 'S_M_Y_AMMUCITY_01_WHITE_MINI_01'],
	s_m_y_baywatch_01: ['S_M_Y_BAYWATCH_01_BLACK_FULL_01', 'S_M_Y_BAYWATCH_01_BLACK_FULL_02', 'S_M_Y_BAYWATCH_01_WHITE_FULL_01', 'S_M_Y_BAYWATCH_01_WHITE_FULL_02'],
	s_m_y_genericcheapworker_01: ['S_M_Y_GENERICCHEAPWORKER_01_BLACK_MINI_01', 'S_M_Y_GENERICCHEAPWORKER_01_BLACK_MINI_02', 'S_M_Y_GENERICCHEAPWORKER_01_WHITE_MINI_01'],
	s_m_y_genericworker_01: ['S_M_Y_GENERICWORKER_01_BLACK_MINI_01', 'S_M_Y_GENERICWORKER_01_BLACK_MINI_02', 'S_M_Y_GENERICWORKER_01_LATINO_MINI_01', 'S_M_Y_GENERICWORKER_01_LATINO_MINI_02', 'S_M_Y_GENERICWORKER_01_WHITE_MINI_01', 'S_M_Y_GENERICWORKER_01_WHITE_MINI_02'],
	s_m_y_shop_mask: ['S_M_Y_SHOP_MASK_WHITE_MINI_01'],
	u_m_y_tattoo_01: ['U_M_Y_TATTOO_01_WHITE_MINI_01'],
});

/** Stand-ins for a model with no voice of its own that can make the call. */
export const POLICE_CALL_FALLBACK_VOICES = Object.freeze({
	female: 'A_F_M_SALTON_01_WHITE_MINI_03',
	male: 'A_M_M_EASTSA_02_LATINO_MINI_01',
});
