/*
 * Turn dropped-in content packs into FiveM resources.
 *
 * Packs are DISCOVERED: every resources/[dlc]/dlc_<name>/ folder is one. Drop the streamed files
 * (.ydr .ydd .yft .ytd .ymap .ytyp .ycd .ybn) into its stream/ and the .meta files into data/, run
 * this, and the manifest is generated from what is on disk and the ensure line added to
 * resources.dlc.cfg. A pack nobody has filled yet is an empty resource that starts cleanly.
 *
 *   npm run dlc                    scaffold + regenerate every manifest, and report
 *   node ./scripts/dlc.js --check  report only, change nothing
 */
const fs = require('fs');
const path = require('path');
const { createHash } = require('crypto');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'resources', '[dlc]');
const CHECK_ONLY = process.argv.includes('--check');

/**
 * Optional notes per pack: `{ kind: 'map' | 'vehicle', note: '...' }`. A pack absent from here
 * still works; its kind is inferred from its contents.
 */
const KNOWN = {};

/** Which `data_file` a meta file needs, by filename. */
const DATA_FILES = {
	'vehicles.meta': 'VEHICLE_METADATA_FILE',
	'carcols.meta': 'CARCOLS_FILE',
	'carvariations.meta': 'VEHICLE_VARIATION_FILE',
	'handling.meta': 'HANDLING_FILE',
	'vehiclelayouts.meta': 'VEHICLE_LAYOUTS_FILE',
	'contentunlocks.meta': 'CONTENT_UNLOCKING_META_FILE',
	'weaponarchetypes.meta': 'WEAPON_METADATA_FILE',
	'peds.meta': 'PED_METADATA_FILE',
	'pedpersonality.meta': 'PED_PERSONALITY_FILE',
	'conditionalanims.meta': 'CONDITIONAL_ANIMS_FILE',
};

/** Meta files FiveM has no data_file type for, and what to do instead. */
const UNSUPPORTED_DATA_FILES = {
	'dlctext.meta': 'FiveM rejects DLCTEXT_FILE; use AddTextEntry for the display name instead',
};

const listFiles = dir => (fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => !f.startsWith('.')) : []);

/** A RAGE file's magic and resource version, which catch a file saved under the wrong name. */
const headerOf = file => {
	const fd = fs.openSync(file, 'r');
	const buffer = Buffer.alloc(8);

	try {
		fs.readSync(fd, buffer, 0, 8, 0);
	} finally {
		fs.closeSync(fd);
	}
	return {
		magic: buffer.toString('latin1', 0, 4),
		version: buffer.toString('latin1', 0, 4) === 'RSC7' ? buffer.readUInt32LE(4) : null,
	};
};

const lodBase = name => name.toLowerCase().replace(/^hi@/, '').replace(/_hi(.[^.]+)$/, '$1');

const EXPECTED_VERSION = { '.ybn': [43], '.ydr': [165], '.ydd': [165], '.yft': [162], '.ytd': [13], '.ymap': [2], '.ytyp': [2] };
const VERSION_NAMES = { 2: 'a ymap or ytyp', 13: 'a texture dictionary', 43: 'collision bounds', 162: 'a fragment (.yft)', 165: 'a drawable (.ydr/.ydd)' };
const EXPECTED_MAGIC = {
	'.ybn': ['RSC7'], '.ydr': ['RSC7'], '.ydd': ['RSC7'], '.yft': ['RSC7'], '.ytd': ['RSC7'], '.ycd': ['RSC7'],
	'.ymap': ['RSC7', 'PSIN'], '.ytyp': ['RSC7', 'PSIN'], '.ymf': ['PSIN', 'RSC7'],
};

const inferKind = (streamed, metas) => {
	const has = ext => streamed.some(f => f.toLowerCase().endsWith(ext));

	if(metas.some(m => m.toLowerCase() === 'vehicles.meta')) {
		return 'vehicle';
	}
	if(has('.ymap') || has('.ybn')) {
		return 'map';
	}
	return has('.yft') ? 'vehicle' : 'map';
};

const manifestFor = (name, pack, streamed, metas, ytyps) => {
	const lines = [
		'-- Generated by base/scripts/dlc.js. Edit that, not this.',
		`-- ${pack.note ?? `${name}`}`,
		'',
		'fx_version \'cerulean\'',
		'game \'gta5\'',
		'',
		`description '${(pack.note ?? name).replace(/'/g, '')}'`,
		'',
	];

	if(pack.kind === 'map') {
		lines.push('this_is_a_map \'yes\'', '');
	}
	if(!streamed.length) {
		lines.push('-- Nothing here yet: stream/ is empty, so this resource streams nothing.');
		return lines.join('\n') + '\n';
	}
	lines.push(`-- ${streamed.length} streamed asset(s) in stream/.`, '');

	if(metas.length || ytyps.length) {
		lines.push('files {');
		for(const meta of metas) {
			if(DATA_FILES[meta.toLowerCase()]) {
				lines.push(`\t'data/${meta}',`);
			}
		}
		for(const ytyp of ytyps) {
			lines.push(`\t'stream/${ytyp}',`);
		}
		lines.push('}', '');
	}
	for(const meta of metas) {
		const key = DATA_FILES[meta.toLowerCase()];
		const unsupported = UNSUPPORTED_DATA_FILES[meta.toLowerCase()];

		if(key) {
			lines.push(`data_file '${key}' 'data/${meta}'`);
		} else if(unsupported) {
			lines.push(`-- data/${meta}: not declared. ${unsupported}.`);
		} else {
			lines.push(`-- data/${meta}: no known data_file key. Add it to DATA_FILES in scripts/dlc.js.`);
		}
	}
	if(metas.length) {
		lines.push('');
	}
	// Every .ytyp has to be requested by name or its archetypes resolve to nothing.
	for(const ytyp of ytyps) {
		lines.push(`data_file 'DLC_ITYP_REQUEST' 'stream/${ytyp}'`);
	}
	return lines.join('\n') + '\n';
};

fs.mkdirSync(OUT, { recursive: true });

const discovered = fs.readdirSync(OUT, { withFileTypes: true })
	.filter(e => e.isDirectory() && e.name.startsWith('dlc_'))
	.map(e => e.name);

for(const name of Object.keys(KNOWN)) {
	if(!discovered.includes(`dlc_${name}`)) {
		discovered.push(`dlc_${name}`);
	}
}
discovered.sort();

const report = [];

for(const folder of discovered) {
	const name = folder.replace(/^dlc_/, '');
	const dir = path.join(OUT, folder);
	const streamDir = path.join(dir, 'stream');
	const dataDir = path.join(dir, 'data');

	if(!CHECK_ONLY) {
		fs.mkdirSync(streamDir, { recursive: true });
		fs.mkdirSync(dataDir, { recursive: true });
	}

	const streamed = listFiles(streamDir);
	const metas = listFiles(dataDir).filter(f => f.toLowerCase().endsWith('.meta'));
	const ytyps = streamed.filter(f => f.toLowerCase().endsWith('.ytyp'));
	const known = KNOWN[name];
	const pack = { kind: known?.kind ?? inferKind(streamed, metas), note: known?.note };
	const has = ext => streamed.some(f => f.toLowerCase().endsWith(ext));
	const warnings = [];
	const notes = [];

	// A pre-2019 manifest beside a generated one is two manifests disagreeing about one resource.
	const legacy = path.join(dir, '__resource.lua');

	if(fs.existsSync(legacy)) {
		if(CHECK_ONLY) {
			notes.push('has a legacy __resource.lua, superseded by the generated fxmanifest.lua');
		} else {
			fs.rmSync(legacy);
			notes.push('removed a legacy __resource.lua');
		}
	}
	if(pack.kind === 'vehicle' && has('.yft') && !metas.some(m => m.toLowerCase() === 'vehicles.meta')) {
		warnings.push('no vehicles.meta: models stream but cannot be spawned');
	}
	if((has('.ydr') || has('.ydd')) && !ytyps.length) {
		notes.push('models with no .ytyp: fine if they replace vanilla archetypes, missing if they define new ones');
	}

	const digests = new Map();

	for(const file of streamed) {
		const full = path.join(streamDir, file);
		const ext = path.extname(file).toLowerCase();
		const expected = EXPECTED_MAGIC[ext];
		const header = expected || EXPECTED_VERSION[ext] ? headerOf(full) : null;

		if(expected && header && !expected.includes(header.magic)) {
			warnings.push(`${file} is ${JSON.stringify(header.magic)}, not ${expected.join(' or ')}: wrong file under this name`);
		}

		const versions = EXPECTED_VERSION[ext];

		if(versions && header?.version !== null && header?.version !== undefined && !versions.includes(header.version)) {
			warnings.push(`${file} is ${VERSION_NAMES[header.version] ?? `resource version ${header.version}`}, not ${ext}`);
		}

		const digest = createHash('md5').update(fs.readFileSync(full)).digest('hex');
		const twin = digests.get(digest);

		if(twin && lodBase(file) !== lodBase(twin)) {
			warnings.push(`${file} is byte-identical to ${twin}: one of them is misnamed`);
		}
		if(!twin) {
			digests.set(digest, file);
		}
	}

	if(has('.ymap') && !streamed.some(f => f.toLowerCase() === '_manifest.ymf')) {
		if(streamed.some(f => /milo/i.test(f) && f.toLowerCase().endsWith('.ymap'))) {
			warnings.push('MLO ymap with no _manifest.ymf: this crashes the game on load, re-export it');
		} else {
			notes.push('.ymap with no _manifest.ymf: interior dependencies may not resolve');
		}
	}

	if(!CHECK_ONLY) {
		fs.writeFileSync(path.join(dir, 'fxmanifest.lua'), manifestFor(name, pack, streamed, metas, ytyps), 'utf8');
	}
	report.push({ folder, kind: pack.kind + (known ? '' : '?'), streamed: streamed.length, metas: metas.length, ytyps: ytyps.length, warnings, notes });
}

// The ensure list in resources.dlc.cfg, between its markers.
const CFG = path.join(ROOT, 'resources.dlc.cfg');
const OPEN = '# >>> dlc packs — generated by base/scripts/dlc.js';
const CLOSE = '# <<< dlc packs';

const writeEnsures = () => {
	const cfgRaw = fs.readFileSync(CFG, 'utf8');
	const cfgCrlf = /\r\n/.test(cfgRaw);
	const cfg = cfgRaw.replace(/\r\n/g, '\n');
	const wanted = [OPEN, ...report.map(r => `ensure ${r.folder}`), CLOSE].join('\n');
	const start = cfg.indexOf(OPEN);
	const end = cfg.indexOf(CLOSE);

	if(start < 0 || end <= start) {
		console.warn('  resources.dlc.cfg has lost its generated-block markers: skipped.');
		return false;
	}

	const next = cfg.slice(0, start) + wanted + cfg.slice(end + CLOSE.length);

	if(next === cfg) {
		return false;
	}
	fs.writeFileSync(CFG, cfgCrlf ? next.replace(/\n/g, '\r\n') : next, 'utf8');
	return true;
};

const ensuresChanged = CHECK_ONLY ? false : writeEnsures();

if(!CHECK_ONLY) {
	fs.writeFileSync(path.join(OUT, 'README.md'), [
		'# Content packs',
		'',
		'Generated by `base/scripts/dlc.js`. Everything here is build output except `*/stream/` and',
		'`*/data/`, which are tracked.',
		'',
		'Adding a pack: `mkdir dlc_<name>/stream`, drop the files in, run `npm run dlc` inside base/.',
		'See docs/dlcpacks.md.',
		'',
	].join('\n'), 'utf8');
}

// Two packs shipping the same filename is one of them winning arbitrarily.
const PER_RESOURCE = new Set(['_manifest.ymf']);
const owners = new Map();

for(const folder of discovered) {
	for(const file of listFiles(path.join(OUT, folder, 'stream'))) {
		const key = file.toLowerCase();

		if(!PER_RESOURCE.has(key)) {
			owners.set(key, [...(owners.get(key) ?? []), folder]);
		}
	}
}
for(const [file, packs] of [...owners].filter(([, packs]) => packs.length > 1)) {
	for(const folder of packs) {
		report.find(r => r.folder === folder)?.warnings.push(`${file} also ships in ${packs.filter(p => p !== folder).join(', ')}`);
	}
}

console.log('');
console.log('  resource                     kind      stream   meta   ytyp   status');
for(const r of report) {
	const status = r.warnings.length ? `INCOMPLETE: ${r.warnings[0]}` : r.streamed ? 'ready' : 'EMPTY';

	console.log('  ' + r.folder.padEnd(29) + r.kind.padEnd(10) + String(r.streamed).padStart(6) + String(r.metas).padStart(7) + String(r.ytyps).padStart(7) + '   ' + status);
}
if(!report.length) {
	console.log('  (no packs: create resources/[dlc]/dlc_<name>/stream and drop files in)');
}
console.log('');
console.log(CHECK_ONLY ? '  (--check: nothing written)' : `  ${report.length} manifest(s) written to resources/[dlc]/`);
if(ensuresChanged) {
	console.log('  resources.dlc.cfg ensure block updated.');
}
for(const r of report.filter(r => r.warnings.length || r.notes.length)) {
	for(const line of [...r.warnings, ...r.notes]) {
		console.log(`  ${r.folder}: ${line}`);
	}
}
console.log('');
